
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AgentResponse` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AgentResponse
 * 
 */
export type AgentResponseModel = runtime.Types.Result.DefaultSelection<Prisma.$AgentResponsePayload>

export type AggregateAgentResponse = {
  _count: AgentResponseCountAggregateOutputType | null
  _min: AgentResponseMinAggregateOutputType | null
  _max: AgentResponseMaxAggregateOutputType | null
}

export type AgentResponseMinAggregateOutputType = {
  id: string | null
  type: string | null
  text: string | null
  timestamp: Date | null
  chatId: string | null
  userRequestId: string | null
}

export type AgentResponseMaxAggregateOutputType = {
  id: string | null
  type: string | null
  text: string | null
  timestamp: Date | null
  chatId: string | null
  userRequestId: string | null
}

export type AgentResponseCountAggregateOutputType = {
  id: number
  type: number
  text: number
  timestamp: number
  chatId: number
  userRequestId: number
  _all: number
}


export type AgentResponseMinAggregateInputType = {
  id?: true
  type?: true
  text?: true
  timestamp?: true
  chatId?: true
  userRequestId?: true
}

export type AgentResponseMaxAggregateInputType = {
  id?: true
  type?: true
  text?: true
  timestamp?: true
  chatId?: true
  userRequestId?: true
}

export type AgentResponseCountAggregateInputType = {
  id?: true
  type?: true
  text?: true
  timestamp?: true
  chatId?: true
  userRequestId?: true
  _all?: true
}

export type AgentResponseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgentResponse to aggregate.
   */
  where?: Prisma.AgentResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentResponses to fetch.
   */
  orderBy?: Prisma.AgentResponseOrderByWithRelationInput | Prisma.AgentResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AgentResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AgentResponses
  **/
  _count?: true | AgentResponseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgentResponseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgentResponseMaxAggregateInputType
}

export type GetAgentResponseAggregateType<T extends AgentResponseAggregateArgs> = {
      [P in keyof T & keyof AggregateAgentResponse]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgentResponse[P]>
    : Prisma.GetScalarType<T[P], AggregateAgentResponse[P]>
}




export type AgentResponseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgentResponseWhereInput
  orderBy?: Prisma.AgentResponseOrderByWithAggregationInput | Prisma.AgentResponseOrderByWithAggregationInput[]
  by: Prisma.AgentResponseScalarFieldEnum[] | Prisma.AgentResponseScalarFieldEnum
  having?: Prisma.AgentResponseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgentResponseCountAggregateInputType | true
  _min?: AgentResponseMinAggregateInputType
  _max?: AgentResponseMaxAggregateInputType
}

export type AgentResponseGroupByOutputType = {
  id: string
  type: string
  text: string
  timestamp: Date
  chatId: string
  userRequestId: string | null
  _count: AgentResponseCountAggregateOutputType | null
  _min: AgentResponseMinAggregateOutputType | null
  _max: AgentResponseMaxAggregateOutputType | null
}

type GetAgentResponseGroupByPayload<T extends AgentResponseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgentResponseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgentResponseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgentResponseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgentResponseGroupByOutputType[P]>
      }
    >
  >



export type AgentResponseWhereInput = {
  AND?: Prisma.AgentResponseWhereInput | Prisma.AgentResponseWhereInput[]
  OR?: Prisma.AgentResponseWhereInput[]
  NOT?: Prisma.AgentResponseWhereInput | Prisma.AgentResponseWhereInput[]
  id?: Prisma.StringFilter<"AgentResponse"> | string
  type?: Prisma.StringFilter<"AgentResponse"> | string
  text?: Prisma.StringFilter<"AgentResponse"> | string
  timestamp?: Prisma.DateTimeFilter<"AgentResponse"> | Date | string
  chatId?: Prisma.StringFilter<"AgentResponse"> | string
  userRequestId?: Prisma.StringNullableFilter<"AgentResponse"> | string | null
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
  userRequest?: Prisma.XOR<Prisma.UserRequestNullableScalarRelationFilter, Prisma.UserRequestWhereInput> | null
}

export type AgentResponseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  text?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  userRequestId?: Prisma.SortOrderInput | Prisma.SortOrder
  chat?: Prisma.ChatOrderByWithRelationInput
  userRequest?: Prisma.UserRequestOrderByWithRelationInput
}

export type AgentResponseWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userRequestId?: string
  AND?: Prisma.AgentResponseWhereInput | Prisma.AgentResponseWhereInput[]
  OR?: Prisma.AgentResponseWhereInput[]
  NOT?: Prisma.AgentResponseWhereInput | Prisma.AgentResponseWhereInput[]
  type?: Prisma.StringFilter<"AgentResponse"> | string
  text?: Prisma.StringFilter<"AgentResponse"> | string
  timestamp?: Prisma.DateTimeFilter<"AgentResponse"> | Date | string
  chatId?: Prisma.StringFilter<"AgentResponse"> | string
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
  userRequest?: Prisma.XOR<Prisma.UserRequestNullableScalarRelationFilter, Prisma.UserRequestWhereInput> | null
}, "id" | "userRequestId">

export type AgentResponseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  text?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  userRequestId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AgentResponseCountOrderByAggregateInput
  _max?: Prisma.AgentResponseMaxOrderByAggregateInput
  _min?: Prisma.AgentResponseMinOrderByAggregateInput
}

export type AgentResponseScalarWhereWithAggregatesInput = {
  AND?: Prisma.AgentResponseScalarWhereWithAggregatesInput | Prisma.AgentResponseScalarWhereWithAggregatesInput[]
  OR?: Prisma.AgentResponseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AgentResponseScalarWhereWithAggregatesInput | Prisma.AgentResponseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AgentResponse"> | string
  type?: Prisma.StringWithAggregatesFilter<"AgentResponse"> | string
  text?: Prisma.StringWithAggregatesFilter<"AgentResponse"> | string
  timestamp?: Prisma.DateTimeWithAggregatesFilter<"AgentResponse"> | Date | string
  chatId?: Prisma.StringWithAggregatesFilter<"AgentResponse"> | string
  userRequestId?: Prisma.StringNullableWithAggregatesFilter<"AgentResponse"> | string | null
}

export type AgentResponseCreateInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  userRequestId?: string | null
  chat: Prisma.ChatCreateNestedOneWithoutAgentResponsesInput
  userRequest?: Prisma.UserRequestCreateNestedOneWithoutAgentResponseInput
}

export type AgentResponseUncheckedCreateInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  chatId: string
  userRequestId?: string | null
  userRequest?: Prisma.UserRequestUncheckedCreateNestedOneWithoutAgentResponseInput
}

export type AgentResponseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRequestId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chat?: Prisma.ChatUpdateOneRequiredWithoutAgentResponsesNestedInput
  userRequest?: Prisma.UserRequestUpdateOneWithoutAgentResponseNestedInput
}

export type AgentResponseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  userRequestId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userRequest?: Prisma.UserRequestUncheckedUpdateOneWithoutAgentResponseNestedInput
}

export type AgentResponseCreateManyInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  chatId: string
  userRequestId?: string | null
}

export type AgentResponseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRequestId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AgentResponseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  userRequestId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AgentResponseListRelationFilter = {
  every?: Prisma.AgentResponseWhereInput
  some?: Prisma.AgentResponseWhereInput
  none?: Prisma.AgentResponseWhereInput
}

export type AgentResponseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AgentResponseNullableScalarRelationFilter = {
  is?: Prisma.AgentResponseWhereInput | null
  isNot?: Prisma.AgentResponseWhereInput | null
}

export type AgentResponseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  text?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  userRequestId?: Prisma.SortOrder
}

export type AgentResponseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  text?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  userRequestId?: Prisma.SortOrder
}

export type AgentResponseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  text?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  userRequestId?: Prisma.SortOrder
}

export type AgentResponseCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.AgentResponseCreateWithoutChatInput, Prisma.AgentResponseUncheckedCreateWithoutChatInput> | Prisma.AgentResponseCreateWithoutChatInput[] | Prisma.AgentResponseUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.AgentResponseCreateOrConnectWithoutChatInput | Prisma.AgentResponseCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.AgentResponseCreateManyChatInputEnvelope
  connect?: Prisma.AgentResponseWhereUniqueInput | Prisma.AgentResponseWhereUniqueInput[]
}

export type AgentResponseUncheckedCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.AgentResponseCreateWithoutChatInput, Prisma.AgentResponseUncheckedCreateWithoutChatInput> | Prisma.AgentResponseCreateWithoutChatInput[] | Prisma.AgentResponseUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.AgentResponseCreateOrConnectWithoutChatInput | Prisma.AgentResponseCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.AgentResponseCreateManyChatInputEnvelope
  connect?: Prisma.AgentResponseWhereUniqueInput | Prisma.AgentResponseWhereUniqueInput[]
}

export type AgentResponseUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.AgentResponseCreateWithoutChatInput, Prisma.AgentResponseUncheckedCreateWithoutChatInput> | Prisma.AgentResponseCreateWithoutChatInput[] | Prisma.AgentResponseUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.AgentResponseCreateOrConnectWithoutChatInput | Prisma.AgentResponseCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.AgentResponseUpsertWithWhereUniqueWithoutChatInput | Prisma.AgentResponseUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.AgentResponseCreateManyChatInputEnvelope
  set?: Prisma.AgentResponseWhereUniqueInput | Prisma.AgentResponseWhereUniqueInput[]
  disconnect?: Prisma.AgentResponseWhereUniqueInput | Prisma.AgentResponseWhereUniqueInput[]
  delete?: Prisma.AgentResponseWhereUniqueInput | Prisma.AgentResponseWhereUniqueInput[]
  connect?: Prisma.AgentResponseWhereUniqueInput | Prisma.AgentResponseWhereUniqueInput[]
  update?: Prisma.AgentResponseUpdateWithWhereUniqueWithoutChatInput | Prisma.AgentResponseUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.AgentResponseUpdateManyWithWhereWithoutChatInput | Prisma.AgentResponseUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.AgentResponseScalarWhereInput | Prisma.AgentResponseScalarWhereInput[]
}

export type AgentResponseUncheckedUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.AgentResponseCreateWithoutChatInput, Prisma.AgentResponseUncheckedCreateWithoutChatInput> | Prisma.AgentResponseCreateWithoutChatInput[] | Prisma.AgentResponseUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.AgentResponseCreateOrConnectWithoutChatInput | Prisma.AgentResponseCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.AgentResponseUpsertWithWhereUniqueWithoutChatInput | Prisma.AgentResponseUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.AgentResponseCreateManyChatInputEnvelope
  set?: Prisma.AgentResponseWhereUniqueInput | Prisma.AgentResponseWhereUniqueInput[]
  disconnect?: Prisma.AgentResponseWhereUniqueInput | Prisma.AgentResponseWhereUniqueInput[]
  delete?: Prisma.AgentResponseWhereUniqueInput | Prisma.AgentResponseWhereUniqueInput[]
  connect?: Prisma.AgentResponseWhereUniqueInput | Prisma.AgentResponseWhereUniqueInput[]
  update?: Prisma.AgentResponseUpdateWithWhereUniqueWithoutChatInput | Prisma.AgentResponseUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.AgentResponseUpdateManyWithWhereWithoutChatInput | Prisma.AgentResponseUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.AgentResponseScalarWhereInput | Prisma.AgentResponseScalarWhereInput[]
}

export type AgentResponseCreateNestedOneWithoutUserRequestInput = {
  create?: Prisma.XOR<Prisma.AgentResponseCreateWithoutUserRequestInput, Prisma.AgentResponseUncheckedCreateWithoutUserRequestInput>
  connectOrCreate?: Prisma.AgentResponseCreateOrConnectWithoutUserRequestInput
  connect?: Prisma.AgentResponseWhereUniqueInput
}

export type AgentResponseUpdateOneWithoutUserRequestNestedInput = {
  create?: Prisma.XOR<Prisma.AgentResponseCreateWithoutUserRequestInput, Prisma.AgentResponseUncheckedCreateWithoutUserRequestInput>
  connectOrCreate?: Prisma.AgentResponseCreateOrConnectWithoutUserRequestInput
  upsert?: Prisma.AgentResponseUpsertWithoutUserRequestInput
  disconnect?: Prisma.AgentResponseWhereInput | boolean
  delete?: Prisma.AgentResponseWhereInput | boolean
  connect?: Prisma.AgentResponseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AgentResponseUpdateToOneWithWhereWithoutUserRequestInput, Prisma.AgentResponseUpdateWithoutUserRequestInput>, Prisma.AgentResponseUncheckedUpdateWithoutUserRequestInput>
}

export type AgentResponseCreateWithoutChatInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  userRequestId?: string | null
  userRequest?: Prisma.UserRequestCreateNestedOneWithoutAgentResponseInput
}

export type AgentResponseUncheckedCreateWithoutChatInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  userRequestId?: string | null
  userRequest?: Prisma.UserRequestUncheckedCreateNestedOneWithoutAgentResponseInput
}

export type AgentResponseCreateOrConnectWithoutChatInput = {
  where: Prisma.AgentResponseWhereUniqueInput
  create: Prisma.XOR<Prisma.AgentResponseCreateWithoutChatInput, Prisma.AgentResponseUncheckedCreateWithoutChatInput>
}

export type AgentResponseCreateManyChatInputEnvelope = {
  data: Prisma.AgentResponseCreateManyChatInput | Prisma.AgentResponseCreateManyChatInput[]
  skipDuplicates?: boolean
}

export type AgentResponseUpsertWithWhereUniqueWithoutChatInput = {
  where: Prisma.AgentResponseWhereUniqueInput
  update: Prisma.XOR<Prisma.AgentResponseUpdateWithoutChatInput, Prisma.AgentResponseUncheckedUpdateWithoutChatInput>
  create: Prisma.XOR<Prisma.AgentResponseCreateWithoutChatInput, Prisma.AgentResponseUncheckedCreateWithoutChatInput>
}

export type AgentResponseUpdateWithWhereUniqueWithoutChatInput = {
  where: Prisma.AgentResponseWhereUniqueInput
  data: Prisma.XOR<Prisma.AgentResponseUpdateWithoutChatInput, Prisma.AgentResponseUncheckedUpdateWithoutChatInput>
}

export type AgentResponseUpdateManyWithWhereWithoutChatInput = {
  where: Prisma.AgentResponseScalarWhereInput
  data: Prisma.XOR<Prisma.AgentResponseUpdateManyMutationInput, Prisma.AgentResponseUncheckedUpdateManyWithoutChatInput>
}

export type AgentResponseScalarWhereInput = {
  AND?: Prisma.AgentResponseScalarWhereInput | Prisma.AgentResponseScalarWhereInput[]
  OR?: Prisma.AgentResponseScalarWhereInput[]
  NOT?: Prisma.AgentResponseScalarWhereInput | Prisma.AgentResponseScalarWhereInput[]
  id?: Prisma.StringFilter<"AgentResponse"> | string
  type?: Prisma.StringFilter<"AgentResponse"> | string
  text?: Prisma.StringFilter<"AgentResponse"> | string
  timestamp?: Prisma.DateTimeFilter<"AgentResponse"> | Date | string
  chatId?: Prisma.StringFilter<"AgentResponse"> | string
  userRequestId?: Prisma.StringNullableFilter<"AgentResponse"> | string | null
}

export type AgentResponseCreateWithoutUserRequestInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  userRequestId?: string | null
  chat: Prisma.ChatCreateNestedOneWithoutAgentResponsesInput
}

export type AgentResponseUncheckedCreateWithoutUserRequestInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  chatId: string
  userRequestId?: string | null
}

export type AgentResponseCreateOrConnectWithoutUserRequestInput = {
  where: Prisma.AgentResponseWhereUniqueInput
  create: Prisma.XOR<Prisma.AgentResponseCreateWithoutUserRequestInput, Prisma.AgentResponseUncheckedCreateWithoutUserRequestInput>
}

export type AgentResponseUpsertWithoutUserRequestInput = {
  update: Prisma.XOR<Prisma.AgentResponseUpdateWithoutUserRequestInput, Prisma.AgentResponseUncheckedUpdateWithoutUserRequestInput>
  create: Prisma.XOR<Prisma.AgentResponseCreateWithoutUserRequestInput, Prisma.AgentResponseUncheckedCreateWithoutUserRequestInput>
  where?: Prisma.AgentResponseWhereInput
}

export type AgentResponseUpdateToOneWithWhereWithoutUserRequestInput = {
  where?: Prisma.AgentResponseWhereInput
  data: Prisma.XOR<Prisma.AgentResponseUpdateWithoutUserRequestInput, Prisma.AgentResponseUncheckedUpdateWithoutUserRequestInput>
}

export type AgentResponseUpdateWithoutUserRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRequestId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chat?: Prisma.ChatUpdateOneRequiredWithoutAgentResponsesNestedInput
}

export type AgentResponseUncheckedUpdateWithoutUserRequestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  userRequestId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AgentResponseCreateManyChatInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  userRequestId?: string | null
}

export type AgentResponseUpdateWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRequestId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userRequest?: Prisma.UserRequestUpdateOneWithoutAgentResponseNestedInput
}

export type AgentResponseUncheckedUpdateWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRequestId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userRequest?: Prisma.UserRequestUncheckedUpdateOneWithoutAgentResponseNestedInput
}

export type AgentResponseUncheckedUpdateManyWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRequestId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type AgentResponseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  text?: boolean
  timestamp?: boolean
  chatId?: boolean
  userRequestId?: boolean
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  userRequest?: boolean | Prisma.AgentResponse$userRequestArgs<ExtArgs>
}, ExtArgs["result"]["agentResponse"]>

export type AgentResponseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  text?: boolean
  timestamp?: boolean
  chatId?: boolean
  userRequestId?: boolean
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agentResponse"]>

export type AgentResponseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  text?: boolean
  timestamp?: boolean
  chatId?: boolean
  userRequestId?: boolean
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agentResponse"]>

export type AgentResponseSelectScalar = {
  id?: boolean
  type?: boolean
  text?: boolean
  timestamp?: boolean
  chatId?: boolean
  userRequestId?: boolean
}

export type AgentResponseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "text" | "timestamp" | "chatId" | "userRequestId", ExtArgs["result"]["agentResponse"]>
export type AgentResponseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  userRequest?: boolean | Prisma.AgentResponse$userRequestArgs<ExtArgs>
}
export type AgentResponseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}
export type AgentResponseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
}

export type $AgentResponsePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AgentResponse"
  objects: {
    chat: Prisma.$ChatPayload<ExtArgs>
    userRequest: Prisma.$UserRequestPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    type: string
    text: string
    timestamp: Date
    chatId: string
    userRequestId: string | null
  }, ExtArgs["result"]["agentResponse"]>
  composites: {}
}

export type AgentResponseGetPayload<S extends boolean | null | undefined | AgentResponseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AgentResponsePayload, S>

export type AgentResponseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AgentResponseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgentResponseCountAggregateInputType | true
  }

export interface AgentResponseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AgentResponse'], meta: { name: 'AgentResponse' } }
  /**
   * Find zero or one AgentResponse that matches the filter.
   * @param {AgentResponseFindUniqueArgs} args - Arguments to find a AgentResponse
   * @example
   * // Get one AgentResponse
   * const agentResponse = await prisma.agentResponse.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AgentResponseFindUniqueArgs>(args: Prisma.SelectSubset<T, AgentResponseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AgentResponseClient<runtime.Types.Result.GetResult<Prisma.$AgentResponsePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AgentResponse that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AgentResponseFindUniqueOrThrowArgs} args - Arguments to find a AgentResponse
   * @example
   * // Get one AgentResponse
   * const agentResponse = await prisma.agentResponse.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AgentResponseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AgentResponseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgentResponseClient<runtime.Types.Result.GetResult<Prisma.$AgentResponsePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgentResponse that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentResponseFindFirstArgs} args - Arguments to find a AgentResponse
   * @example
   * // Get one AgentResponse
   * const agentResponse = await prisma.agentResponse.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AgentResponseFindFirstArgs>(args?: Prisma.SelectSubset<T, AgentResponseFindFirstArgs<ExtArgs>>): Prisma.Prisma__AgentResponseClient<runtime.Types.Result.GetResult<Prisma.$AgentResponsePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgentResponse that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentResponseFindFirstOrThrowArgs} args - Arguments to find a AgentResponse
   * @example
   * // Get one AgentResponse
   * const agentResponse = await prisma.agentResponse.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AgentResponseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AgentResponseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgentResponseClient<runtime.Types.Result.GetResult<Prisma.$AgentResponsePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AgentResponses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentResponseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AgentResponses
   * const agentResponses = await prisma.agentResponse.findMany()
   * 
   * // Get first 10 AgentResponses
   * const agentResponses = await prisma.agentResponse.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const agentResponseWithIdOnly = await prisma.agentResponse.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AgentResponseFindManyArgs>(args?: Prisma.SelectSubset<T, AgentResponseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentResponsePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AgentResponse.
   * @param {AgentResponseCreateArgs} args - Arguments to create a AgentResponse.
   * @example
   * // Create one AgentResponse
   * const AgentResponse = await prisma.agentResponse.create({
   *   data: {
   *     // ... data to create a AgentResponse
   *   }
   * })
   * 
   */
  create<T extends AgentResponseCreateArgs>(args: Prisma.SelectSubset<T, AgentResponseCreateArgs<ExtArgs>>): Prisma.Prisma__AgentResponseClient<runtime.Types.Result.GetResult<Prisma.$AgentResponsePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AgentResponses.
   * @param {AgentResponseCreateManyArgs} args - Arguments to create many AgentResponses.
   * @example
   * // Create many AgentResponses
   * const agentResponse = await prisma.agentResponse.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AgentResponseCreateManyArgs>(args?: Prisma.SelectSubset<T, AgentResponseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AgentResponses and returns the data saved in the database.
   * @param {AgentResponseCreateManyAndReturnArgs} args - Arguments to create many AgentResponses.
   * @example
   * // Create many AgentResponses
   * const agentResponse = await prisma.agentResponse.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AgentResponses and only return the `id`
   * const agentResponseWithIdOnly = await prisma.agentResponse.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AgentResponseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AgentResponseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentResponsePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AgentResponse.
   * @param {AgentResponseDeleteArgs} args - Arguments to delete one AgentResponse.
   * @example
   * // Delete one AgentResponse
   * const AgentResponse = await prisma.agentResponse.delete({
   *   where: {
   *     // ... filter to delete one AgentResponse
   *   }
   * })
   * 
   */
  delete<T extends AgentResponseDeleteArgs>(args: Prisma.SelectSubset<T, AgentResponseDeleteArgs<ExtArgs>>): Prisma.Prisma__AgentResponseClient<runtime.Types.Result.GetResult<Prisma.$AgentResponsePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AgentResponse.
   * @param {AgentResponseUpdateArgs} args - Arguments to update one AgentResponse.
   * @example
   * // Update one AgentResponse
   * const agentResponse = await prisma.agentResponse.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AgentResponseUpdateArgs>(args: Prisma.SelectSubset<T, AgentResponseUpdateArgs<ExtArgs>>): Prisma.Prisma__AgentResponseClient<runtime.Types.Result.GetResult<Prisma.$AgentResponsePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AgentResponses.
   * @param {AgentResponseDeleteManyArgs} args - Arguments to filter AgentResponses to delete.
   * @example
   * // Delete a few AgentResponses
   * const { count } = await prisma.agentResponse.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AgentResponseDeleteManyArgs>(args?: Prisma.SelectSubset<T, AgentResponseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgentResponses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentResponseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AgentResponses
   * const agentResponse = await prisma.agentResponse.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AgentResponseUpdateManyArgs>(args: Prisma.SelectSubset<T, AgentResponseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgentResponses and returns the data updated in the database.
   * @param {AgentResponseUpdateManyAndReturnArgs} args - Arguments to update many AgentResponses.
   * @example
   * // Update many AgentResponses
   * const agentResponse = await prisma.agentResponse.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AgentResponses and only return the `id`
   * const agentResponseWithIdOnly = await prisma.agentResponse.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AgentResponseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AgentResponseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentResponsePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AgentResponse.
   * @param {AgentResponseUpsertArgs} args - Arguments to update or create a AgentResponse.
   * @example
   * // Update or create a AgentResponse
   * const agentResponse = await prisma.agentResponse.upsert({
   *   create: {
   *     // ... data to create a AgentResponse
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AgentResponse we want to update
   *   }
   * })
   */
  upsert<T extends AgentResponseUpsertArgs>(args: Prisma.SelectSubset<T, AgentResponseUpsertArgs<ExtArgs>>): Prisma.Prisma__AgentResponseClient<runtime.Types.Result.GetResult<Prisma.$AgentResponsePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AgentResponses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentResponseCountArgs} args - Arguments to filter AgentResponses to count.
   * @example
   * // Count the number of AgentResponses
   * const count = await prisma.agentResponse.count({
   *   where: {
   *     // ... the filter for the AgentResponses we want to count
   *   }
   * })
  **/
  count<T extends AgentResponseCountArgs>(
    args?: Prisma.Subset<T, AgentResponseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgentResponseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AgentResponse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentResponseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgentResponseAggregateArgs>(args: Prisma.Subset<T, AgentResponseAggregateArgs>): Prisma.PrismaPromise<GetAgentResponseAggregateType<T>>

  /**
   * Group by AgentResponse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentResponseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AgentResponseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AgentResponseGroupByArgs['orderBy'] }
      : { orderBy?: AgentResponseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AgentResponseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgentResponseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AgentResponse model
 */
readonly fields: AgentResponseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AgentResponse.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AgentResponseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  chat<T extends Prisma.ChatDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChatDefaultArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  userRequest<T extends Prisma.AgentResponse$userRequestArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AgentResponse$userRequestArgs<ExtArgs>>): Prisma.Prisma__UserRequestClient<runtime.Types.Result.GetResult<Prisma.$UserRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AgentResponse model
 */
export interface AgentResponseFieldRefs {
  readonly id: Prisma.FieldRef<"AgentResponse", 'String'>
  readonly type: Prisma.FieldRef<"AgentResponse", 'String'>
  readonly text: Prisma.FieldRef<"AgentResponse", 'String'>
  readonly timestamp: Prisma.FieldRef<"AgentResponse", 'DateTime'>
  readonly chatId: Prisma.FieldRef<"AgentResponse", 'String'>
  readonly userRequestId: Prisma.FieldRef<"AgentResponse", 'String'>
}
    

// Custom InputTypes
/**
 * AgentResponse findUnique
 */
export type AgentResponseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentResponse
   */
  select?: Prisma.AgentResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentResponse
   */
  omit?: Prisma.AgentResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentResponseInclude<ExtArgs> | null
  /**
   * Filter, which AgentResponse to fetch.
   */
  where: Prisma.AgentResponseWhereUniqueInput
}

/**
 * AgentResponse findUniqueOrThrow
 */
export type AgentResponseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentResponse
   */
  select?: Prisma.AgentResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentResponse
   */
  omit?: Prisma.AgentResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentResponseInclude<ExtArgs> | null
  /**
   * Filter, which AgentResponse to fetch.
   */
  where: Prisma.AgentResponseWhereUniqueInput
}

/**
 * AgentResponse findFirst
 */
export type AgentResponseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentResponse
   */
  select?: Prisma.AgentResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentResponse
   */
  omit?: Prisma.AgentResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentResponseInclude<ExtArgs> | null
  /**
   * Filter, which AgentResponse to fetch.
   */
  where?: Prisma.AgentResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentResponses to fetch.
   */
  orderBy?: Prisma.AgentResponseOrderByWithRelationInput | Prisma.AgentResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgentResponses.
   */
  cursor?: Prisma.AgentResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentResponses.
   */
  distinct?: Prisma.AgentResponseScalarFieldEnum | Prisma.AgentResponseScalarFieldEnum[]
}

/**
 * AgentResponse findFirstOrThrow
 */
export type AgentResponseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentResponse
   */
  select?: Prisma.AgentResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentResponse
   */
  omit?: Prisma.AgentResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentResponseInclude<ExtArgs> | null
  /**
   * Filter, which AgentResponse to fetch.
   */
  where?: Prisma.AgentResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentResponses to fetch.
   */
  orderBy?: Prisma.AgentResponseOrderByWithRelationInput | Prisma.AgentResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgentResponses.
   */
  cursor?: Prisma.AgentResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentResponses.
   */
  distinct?: Prisma.AgentResponseScalarFieldEnum | Prisma.AgentResponseScalarFieldEnum[]
}

/**
 * AgentResponse findMany
 */
export type AgentResponseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentResponse
   */
  select?: Prisma.AgentResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentResponse
   */
  omit?: Prisma.AgentResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentResponseInclude<ExtArgs> | null
  /**
   * Filter, which AgentResponses to fetch.
   */
  where?: Prisma.AgentResponseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentResponses to fetch.
   */
  orderBy?: Prisma.AgentResponseOrderByWithRelationInput | Prisma.AgentResponseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AgentResponses.
   */
  cursor?: Prisma.AgentResponseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentResponses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentResponses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentResponses.
   */
  distinct?: Prisma.AgentResponseScalarFieldEnum | Prisma.AgentResponseScalarFieldEnum[]
}

/**
 * AgentResponse create
 */
export type AgentResponseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentResponse
   */
  select?: Prisma.AgentResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentResponse
   */
  omit?: Prisma.AgentResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentResponseInclude<ExtArgs> | null
  /**
   * The data needed to create a AgentResponse.
   */
  data: Prisma.XOR<Prisma.AgentResponseCreateInput, Prisma.AgentResponseUncheckedCreateInput>
}

/**
 * AgentResponse createMany
 */
export type AgentResponseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AgentResponses.
   */
  data: Prisma.AgentResponseCreateManyInput | Prisma.AgentResponseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AgentResponse createManyAndReturn
 */
export type AgentResponseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentResponse
   */
  select?: Prisma.AgentResponseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgentResponse
   */
  omit?: Prisma.AgentResponseOmit<ExtArgs> | null
  /**
   * The data used to create many AgentResponses.
   */
  data: Prisma.AgentResponseCreateManyInput | Prisma.AgentResponseCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentResponseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AgentResponse update
 */
export type AgentResponseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentResponse
   */
  select?: Prisma.AgentResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentResponse
   */
  omit?: Prisma.AgentResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentResponseInclude<ExtArgs> | null
  /**
   * The data needed to update a AgentResponse.
   */
  data: Prisma.XOR<Prisma.AgentResponseUpdateInput, Prisma.AgentResponseUncheckedUpdateInput>
  /**
   * Choose, which AgentResponse to update.
   */
  where: Prisma.AgentResponseWhereUniqueInput
}

/**
 * AgentResponse updateMany
 */
export type AgentResponseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AgentResponses.
   */
  data: Prisma.XOR<Prisma.AgentResponseUpdateManyMutationInput, Prisma.AgentResponseUncheckedUpdateManyInput>
  /**
   * Filter which AgentResponses to update
   */
  where?: Prisma.AgentResponseWhereInput
  /**
   * Limit how many AgentResponses to update.
   */
  limit?: number
}

/**
 * AgentResponse updateManyAndReturn
 */
export type AgentResponseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentResponse
   */
  select?: Prisma.AgentResponseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgentResponse
   */
  omit?: Prisma.AgentResponseOmit<ExtArgs> | null
  /**
   * The data used to update AgentResponses.
   */
  data: Prisma.XOR<Prisma.AgentResponseUpdateManyMutationInput, Prisma.AgentResponseUncheckedUpdateManyInput>
  /**
   * Filter which AgentResponses to update
   */
  where?: Prisma.AgentResponseWhereInput
  /**
   * Limit how many AgentResponses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentResponseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AgentResponse upsert
 */
export type AgentResponseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentResponse
   */
  select?: Prisma.AgentResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentResponse
   */
  omit?: Prisma.AgentResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentResponseInclude<ExtArgs> | null
  /**
   * The filter to search for the AgentResponse to update in case it exists.
   */
  where: Prisma.AgentResponseWhereUniqueInput
  /**
   * In case the AgentResponse found by the `where` argument doesn't exist, create a new AgentResponse with this data.
   */
  create: Prisma.XOR<Prisma.AgentResponseCreateInput, Prisma.AgentResponseUncheckedCreateInput>
  /**
   * In case the AgentResponse was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AgentResponseUpdateInput, Prisma.AgentResponseUncheckedUpdateInput>
}

/**
 * AgentResponse delete
 */
export type AgentResponseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentResponse
   */
  select?: Prisma.AgentResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentResponse
   */
  omit?: Prisma.AgentResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentResponseInclude<ExtArgs> | null
  /**
   * Filter which AgentResponse to delete.
   */
  where: Prisma.AgentResponseWhereUniqueInput
}

/**
 * AgentResponse deleteMany
 */
export type AgentResponseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgentResponses to delete
   */
  where?: Prisma.AgentResponseWhereInput
  /**
   * Limit how many AgentResponses to delete.
   */
  limit?: number
}

/**
 * AgentResponse.userRequest
 */
export type AgentResponse$userRequestArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRequest
   */
  select?: Prisma.UserRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRequest
   */
  omit?: Prisma.UserRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRequestInclude<ExtArgs> | null
  where?: Prisma.UserRequestWhereInput
}

/**
 * AgentResponse without action
 */
export type AgentResponseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentResponse
   */
  select?: Prisma.AgentResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentResponse
   */
  omit?: Prisma.AgentResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentResponseInclude<ExtArgs> | null
}
