
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserRequest` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserRequest
 * 
 */
export type UserRequestModel = runtime.Types.Result.DefaultSelection<Prisma.$UserRequestPayload>

export type AggregateUserRequest = {
  _count: UserRequestCountAggregateOutputType | null
  _min: UserRequestMinAggregateOutputType | null
  _max: UserRequestMaxAggregateOutputType | null
}

export type UserRequestMinAggregateOutputType = {
  id: string | null
  type: string | null
  text: string | null
  timestamp: Date | null
  chatId: string | null
  agentResponseId: string | null
}

export type UserRequestMaxAggregateOutputType = {
  id: string | null
  type: string | null
  text: string | null
  timestamp: Date | null
  chatId: string | null
  agentResponseId: string | null
}

export type UserRequestCountAggregateOutputType = {
  id: number
  type: number
  text: number
  timestamp: number
  chatId: number
  agentResponseId: number
  _all: number
}


export type UserRequestMinAggregateInputType = {
  id?: true
  type?: true
  text?: true
  timestamp?: true
  chatId?: true
  agentResponseId?: true
}

export type UserRequestMaxAggregateInputType = {
  id?: true
  type?: true
  text?: true
  timestamp?: true
  chatId?: true
  agentResponseId?: true
}

export type UserRequestCountAggregateInputType = {
  id?: true
  type?: true
  text?: true
  timestamp?: true
  chatId?: true
  agentResponseId?: true
  _all?: true
}

export type UserRequestAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserRequest to aggregate.
   */
  where?: Prisma.UserRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRequests to fetch.
   */
  orderBy?: Prisma.UserRequestOrderByWithRelationInput | Prisma.UserRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserRequests
  **/
  _count?: true | UserRequestCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserRequestMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserRequestMaxAggregateInputType
}

export type GetUserRequestAggregateType<T extends UserRequestAggregateArgs> = {
      [P in keyof T & keyof AggregateUserRequest]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserRequest[P]>
    : Prisma.GetScalarType<T[P], AggregateUserRequest[P]>
}




export type UserRequestGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserRequestWhereInput
  orderBy?: Prisma.UserRequestOrderByWithAggregationInput | Prisma.UserRequestOrderByWithAggregationInput[]
  by: Prisma.UserRequestScalarFieldEnum[] | Prisma.UserRequestScalarFieldEnum
  having?: Prisma.UserRequestScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserRequestCountAggregateInputType | true
  _min?: UserRequestMinAggregateInputType
  _max?: UserRequestMaxAggregateInputType
}

export type UserRequestGroupByOutputType = {
  id: string
  type: string
  text: string
  timestamp: Date
  chatId: string
  agentResponseId: string | null
  _count: UserRequestCountAggregateOutputType | null
  _min: UserRequestMinAggregateOutputType | null
  _max: UserRequestMaxAggregateOutputType | null
}

type GetUserRequestGroupByPayload<T extends UserRequestGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserRequestGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserRequestGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserRequestGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserRequestGroupByOutputType[P]>
      }
    >
  >



export type UserRequestWhereInput = {
  AND?: Prisma.UserRequestWhereInput | Prisma.UserRequestWhereInput[]
  OR?: Prisma.UserRequestWhereInput[]
  NOT?: Prisma.UserRequestWhereInput | Prisma.UserRequestWhereInput[]
  id?: Prisma.StringFilter<"UserRequest"> | string
  type?: Prisma.StringFilter<"UserRequest"> | string
  text?: Prisma.StringFilter<"UserRequest"> | string
  timestamp?: Prisma.DateTimeFilter<"UserRequest"> | Date | string
  chatId?: Prisma.StringFilter<"UserRequest"> | string
  agentResponseId?: Prisma.StringNullableFilter<"UserRequest"> | string | null
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
  agentResponse?: Prisma.XOR<Prisma.AgentResponseNullableScalarRelationFilter, Prisma.AgentResponseWhereInput> | null
}

export type UserRequestOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  text?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  agentResponseId?: Prisma.SortOrderInput | Prisma.SortOrder
  chat?: Prisma.ChatOrderByWithRelationInput
  agentResponse?: Prisma.AgentResponseOrderByWithRelationInput
}

export type UserRequestWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  agentResponseId?: string
  AND?: Prisma.UserRequestWhereInput | Prisma.UserRequestWhereInput[]
  OR?: Prisma.UserRequestWhereInput[]
  NOT?: Prisma.UserRequestWhereInput | Prisma.UserRequestWhereInput[]
  type?: Prisma.StringFilter<"UserRequest"> | string
  text?: Prisma.StringFilter<"UserRequest"> | string
  timestamp?: Prisma.DateTimeFilter<"UserRequest"> | Date | string
  chatId?: Prisma.StringFilter<"UserRequest"> | string
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
  agentResponse?: Prisma.XOR<Prisma.AgentResponseNullableScalarRelationFilter, Prisma.AgentResponseWhereInput> | null
}, "id" | "agentResponseId">

export type UserRequestOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  text?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  agentResponseId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.UserRequestCountOrderByAggregateInput
  _max?: Prisma.UserRequestMaxOrderByAggregateInput
  _min?: Prisma.UserRequestMinOrderByAggregateInput
}

export type UserRequestScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserRequestScalarWhereWithAggregatesInput | Prisma.UserRequestScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserRequestScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserRequestScalarWhereWithAggregatesInput | Prisma.UserRequestScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserRequest"> | string
  type?: Prisma.StringWithAggregatesFilter<"UserRequest"> | string
  text?: Prisma.StringWithAggregatesFilter<"UserRequest"> | string
  timestamp?: Prisma.DateTimeWithAggregatesFilter<"UserRequest"> | Date | string
  chatId?: Prisma.StringWithAggregatesFilter<"UserRequest"> | string
  agentResponseId?: Prisma.StringNullableWithAggregatesFilter<"UserRequest"> | string | null
}

export type UserRequestCreateInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  chat: Prisma.ChatCreateNestedOneWithoutUserRequestsInput
  agentResponse?: Prisma.AgentResponseCreateNestedOneWithoutUserRequestInput
}

export type UserRequestUncheckedCreateInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  chatId: string
  agentResponseId?: string | null
}

export type UserRequestUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chat?: Prisma.ChatUpdateOneRequiredWithoutUserRequestsNestedInput
  agentResponse?: Prisma.AgentResponseUpdateOneWithoutUserRequestNestedInput
}

export type UserRequestUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  agentResponseId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type UserRequestCreateManyInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  chatId: string
  agentResponseId?: string | null
}

export type UserRequestUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserRequestUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  agentResponseId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type UserRequestListRelationFilter = {
  every?: Prisma.UserRequestWhereInput
  some?: Prisma.UserRequestWhereInput
  none?: Prisma.UserRequestWhereInput
}

export type UserRequestOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserRequestCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  text?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  agentResponseId?: Prisma.SortOrder
}

export type UserRequestMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  text?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  agentResponseId?: Prisma.SortOrder
}

export type UserRequestMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  text?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  chatId?: Prisma.SortOrder
  agentResponseId?: Prisma.SortOrder
}

export type UserRequestNullableScalarRelationFilter = {
  is?: Prisma.UserRequestWhereInput | null
  isNot?: Prisma.UserRequestWhereInput | null
}

export type UserRequestCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.UserRequestCreateWithoutChatInput, Prisma.UserRequestUncheckedCreateWithoutChatInput> | Prisma.UserRequestCreateWithoutChatInput[] | Prisma.UserRequestUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.UserRequestCreateOrConnectWithoutChatInput | Prisma.UserRequestCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.UserRequestCreateManyChatInputEnvelope
  connect?: Prisma.UserRequestWhereUniqueInput | Prisma.UserRequestWhereUniqueInput[]
}

export type UserRequestUncheckedCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.UserRequestCreateWithoutChatInput, Prisma.UserRequestUncheckedCreateWithoutChatInput> | Prisma.UserRequestCreateWithoutChatInput[] | Prisma.UserRequestUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.UserRequestCreateOrConnectWithoutChatInput | Prisma.UserRequestCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.UserRequestCreateManyChatInputEnvelope
  connect?: Prisma.UserRequestWhereUniqueInput | Prisma.UserRequestWhereUniqueInput[]
}

export type UserRequestUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.UserRequestCreateWithoutChatInput, Prisma.UserRequestUncheckedCreateWithoutChatInput> | Prisma.UserRequestCreateWithoutChatInput[] | Prisma.UserRequestUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.UserRequestCreateOrConnectWithoutChatInput | Prisma.UserRequestCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.UserRequestUpsertWithWhereUniqueWithoutChatInput | Prisma.UserRequestUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.UserRequestCreateManyChatInputEnvelope
  set?: Prisma.UserRequestWhereUniqueInput | Prisma.UserRequestWhereUniqueInput[]
  disconnect?: Prisma.UserRequestWhereUniqueInput | Prisma.UserRequestWhereUniqueInput[]
  delete?: Prisma.UserRequestWhereUniqueInput | Prisma.UserRequestWhereUniqueInput[]
  connect?: Prisma.UserRequestWhereUniqueInput | Prisma.UserRequestWhereUniqueInput[]
  update?: Prisma.UserRequestUpdateWithWhereUniqueWithoutChatInput | Prisma.UserRequestUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.UserRequestUpdateManyWithWhereWithoutChatInput | Prisma.UserRequestUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.UserRequestScalarWhereInput | Prisma.UserRequestScalarWhereInput[]
}

export type UserRequestUncheckedUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.UserRequestCreateWithoutChatInput, Prisma.UserRequestUncheckedCreateWithoutChatInput> | Prisma.UserRequestCreateWithoutChatInput[] | Prisma.UserRequestUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.UserRequestCreateOrConnectWithoutChatInput | Prisma.UserRequestCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.UserRequestUpsertWithWhereUniqueWithoutChatInput | Prisma.UserRequestUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.UserRequestCreateManyChatInputEnvelope
  set?: Prisma.UserRequestWhereUniqueInput | Prisma.UserRequestWhereUniqueInput[]
  disconnect?: Prisma.UserRequestWhereUniqueInput | Prisma.UserRequestWhereUniqueInput[]
  delete?: Prisma.UserRequestWhereUniqueInput | Prisma.UserRequestWhereUniqueInput[]
  connect?: Prisma.UserRequestWhereUniqueInput | Prisma.UserRequestWhereUniqueInput[]
  update?: Prisma.UserRequestUpdateWithWhereUniqueWithoutChatInput | Prisma.UserRequestUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.UserRequestUpdateManyWithWhereWithoutChatInput | Prisma.UserRequestUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.UserRequestScalarWhereInput | Prisma.UserRequestScalarWhereInput[]
}

export type UserRequestCreateNestedOneWithoutAgentResponseInput = {
  create?: Prisma.XOR<Prisma.UserRequestCreateWithoutAgentResponseInput, Prisma.UserRequestUncheckedCreateWithoutAgentResponseInput>
  connectOrCreate?: Prisma.UserRequestCreateOrConnectWithoutAgentResponseInput
  connect?: Prisma.UserRequestWhereUniqueInput
}

export type UserRequestUncheckedCreateNestedOneWithoutAgentResponseInput = {
  create?: Prisma.XOR<Prisma.UserRequestCreateWithoutAgentResponseInput, Prisma.UserRequestUncheckedCreateWithoutAgentResponseInput>
  connectOrCreate?: Prisma.UserRequestCreateOrConnectWithoutAgentResponseInput
  connect?: Prisma.UserRequestWhereUniqueInput
}

export type UserRequestUpdateOneWithoutAgentResponseNestedInput = {
  create?: Prisma.XOR<Prisma.UserRequestCreateWithoutAgentResponseInput, Prisma.UserRequestUncheckedCreateWithoutAgentResponseInput>
  connectOrCreate?: Prisma.UserRequestCreateOrConnectWithoutAgentResponseInput
  upsert?: Prisma.UserRequestUpsertWithoutAgentResponseInput
  disconnect?: Prisma.UserRequestWhereInput | boolean
  delete?: Prisma.UserRequestWhereInput | boolean
  connect?: Prisma.UserRequestWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserRequestUpdateToOneWithWhereWithoutAgentResponseInput, Prisma.UserRequestUpdateWithoutAgentResponseInput>, Prisma.UserRequestUncheckedUpdateWithoutAgentResponseInput>
}

export type UserRequestUncheckedUpdateOneWithoutAgentResponseNestedInput = {
  create?: Prisma.XOR<Prisma.UserRequestCreateWithoutAgentResponseInput, Prisma.UserRequestUncheckedCreateWithoutAgentResponseInput>
  connectOrCreate?: Prisma.UserRequestCreateOrConnectWithoutAgentResponseInput
  upsert?: Prisma.UserRequestUpsertWithoutAgentResponseInput
  disconnect?: Prisma.UserRequestWhereInput | boolean
  delete?: Prisma.UserRequestWhereInput | boolean
  connect?: Prisma.UserRequestWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserRequestUpdateToOneWithWhereWithoutAgentResponseInput, Prisma.UserRequestUpdateWithoutAgentResponseInput>, Prisma.UserRequestUncheckedUpdateWithoutAgentResponseInput>
}

export type UserRequestCreateWithoutChatInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  agentResponse?: Prisma.AgentResponseCreateNestedOneWithoutUserRequestInput
}

export type UserRequestUncheckedCreateWithoutChatInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  agentResponseId?: string | null
}

export type UserRequestCreateOrConnectWithoutChatInput = {
  where: Prisma.UserRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.UserRequestCreateWithoutChatInput, Prisma.UserRequestUncheckedCreateWithoutChatInput>
}

export type UserRequestCreateManyChatInputEnvelope = {
  data: Prisma.UserRequestCreateManyChatInput | Prisma.UserRequestCreateManyChatInput[]
  skipDuplicates?: boolean
}

export type UserRequestUpsertWithWhereUniqueWithoutChatInput = {
  where: Prisma.UserRequestWhereUniqueInput
  update: Prisma.XOR<Prisma.UserRequestUpdateWithoutChatInput, Prisma.UserRequestUncheckedUpdateWithoutChatInput>
  create: Prisma.XOR<Prisma.UserRequestCreateWithoutChatInput, Prisma.UserRequestUncheckedCreateWithoutChatInput>
}

export type UserRequestUpdateWithWhereUniqueWithoutChatInput = {
  where: Prisma.UserRequestWhereUniqueInput
  data: Prisma.XOR<Prisma.UserRequestUpdateWithoutChatInput, Prisma.UserRequestUncheckedUpdateWithoutChatInput>
}

export type UserRequestUpdateManyWithWhereWithoutChatInput = {
  where: Prisma.UserRequestScalarWhereInput
  data: Prisma.XOR<Prisma.UserRequestUpdateManyMutationInput, Prisma.UserRequestUncheckedUpdateManyWithoutChatInput>
}

export type UserRequestScalarWhereInput = {
  AND?: Prisma.UserRequestScalarWhereInput | Prisma.UserRequestScalarWhereInput[]
  OR?: Prisma.UserRequestScalarWhereInput[]
  NOT?: Prisma.UserRequestScalarWhereInput | Prisma.UserRequestScalarWhereInput[]
  id?: Prisma.StringFilter<"UserRequest"> | string
  type?: Prisma.StringFilter<"UserRequest"> | string
  text?: Prisma.StringFilter<"UserRequest"> | string
  timestamp?: Prisma.DateTimeFilter<"UserRequest"> | Date | string
  chatId?: Prisma.StringFilter<"UserRequest"> | string
  agentResponseId?: Prisma.StringNullableFilter<"UserRequest"> | string | null
}

export type UserRequestCreateWithoutAgentResponseInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  chat: Prisma.ChatCreateNestedOneWithoutUserRequestsInput
}

export type UserRequestUncheckedCreateWithoutAgentResponseInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  chatId: string
}

export type UserRequestCreateOrConnectWithoutAgentResponseInput = {
  where: Prisma.UserRequestWhereUniqueInput
  create: Prisma.XOR<Prisma.UserRequestCreateWithoutAgentResponseInput, Prisma.UserRequestUncheckedCreateWithoutAgentResponseInput>
}

export type UserRequestUpsertWithoutAgentResponseInput = {
  update: Prisma.XOR<Prisma.UserRequestUpdateWithoutAgentResponseInput, Prisma.UserRequestUncheckedUpdateWithoutAgentResponseInput>
  create: Prisma.XOR<Prisma.UserRequestCreateWithoutAgentResponseInput, Prisma.UserRequestUncheckedCreateWithoutAgentResponseInput>
  where?: Prisma.UserRequestWhereInput
}

export type UserRequestUpdateToOneWithWhereWithoutAgentResponseInput = {
  where?: Prisma.UserRequestWhereInput
  data: Prisma.XOR<Prisma.UserRequestUpdateWithoutAgentResponseInput, Prisma.UserRequestUncheckedUpdateWithoutAgentResponseInput>
}

export type UserRequestUpdateWithoutAgentResponseInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chat?: Prisma.ChatUpdateOneRequiredWithoutUserRequestsNestedInput
}

export type UserRequestUncheckedUpdateWithoutAgentResponseInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserRequestCreateManyChatInput = {
  id?: string
  type: string
  text: string
  timestamp?: Date | string
  agentResponseId?: string | null
}

export type UserRequestUpdateWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agentResponse?: Prisma.AgentResponseUpdateOneWithoutUserRequestNestedInput
}

export type UserRequestUncheckedUpdateWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agentResponseId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type UserRequestUncheckedUpdateManyWithoutChatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  text?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agentResponseId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type UserRequestSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  text?: boolean
  timestamp?: boolean
  chatId?: boolean
  agentResponseId?: boolean
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  agentResponse?: boolean | Prisma.UserRequest$agentResponseArgs<ExtArgs>
}, ExtArgs["result"]["userRequest"]>

export type UserRequestSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  text?: boolean
  timestamp?: boolean
  chatId?: boolean
  agentResponseId?: boolean
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  agentResponse?: boolean | Prisma.UserRequest$agentResponseArgs<ExtArgs>
}, ExtArgs["result"]["userRequest"]>

export type UserRequestSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  text?: boolean
  timestamp?: boolean
  chatId?: boolean
  agentResponseId?: boolean
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  agentResponse?: boolean | Prisma.UserRequest$agentResponseArgs<ExtArgs>
}, ExtArgs["result"]["userRequest"]>

export type UserRequestSelectScalar = {
  id?: boolean
  type?: boolean
  text?: boolean
  timestamp?: boolean
  chatId?: boolean
  agentResponseId?: boolean
}

export type UserRequestOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "text" | "timestamp" | "chatId" | "agentResponseId", ExtArgs["result"]["userRequest"]>
export type UserRequestInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  agentResponse?: boolean | Prisma.UserRequest$agentResponseArgs<ExtArgs>
}
export type UserRequestIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  agentResponse?: boolean | Prisma.UserRequest$agentResponseArgs<ExtArgs>
}
export type UserRequestIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  agentResponse?: boolean | Prisma.UserRequest$agentResponseArgs<ExtArgs>
}

export type $UserRequestPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserRequest"
  objects: {
    chat: Prisma.$ChatPayload<ExtArgs>
    agentResponse: Prisma.$AgentResponsePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    type: string
    text: string
    timestamp: Date
    chatId: string
    agentResponseId: string | null
  }, ExtArgs["result"]["userRequest"]>
  composites: {}
}

export type UserRequestGetPayload<S extends boolean | null | undefined | UserRequestDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserRequestPayload, S>

export type UserRequestCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserRequestFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserRequestCountAggregateInputType | true
  }

export interface UserRequestDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserRequest'], meta: { name: 'UserRequest' } }
  /**
   * Find zero or one UserRequest that matches the filter.
   * @param {UserRequestFindUniqueArgs} args - Arguments to find a UserRequest
   * @example
   * // Get one UserRequest
   * const userRequest = await prisma.userRequest.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserRequestFindUniqueArgs>(args: Prisma.SelectSubset<T, UserRequestFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserRequestClient<runtime.Types.Result.GetResult<Prisma.$UserRequestPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserRequest that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserRequestFindUniqueOrThrowArgs} args - Arguments to find a UserRequest
   * @example
   * // Get one UserRequest
   * const userRequest = await prisma.userRequest.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserRequestFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserRequestFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserRequestClient<runtime.Types.Result.GetResult<Prisma.$UserRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserRequest that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRequestFindFirstArgs} args - Arguments to find a UserRequest
   * @example
   * // Get one UserRequest
   * const userRequest = await prisma.userRequest.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserRequestFindFirstArgs>(args?: Prisma.SelectSubset<T, UserRequestFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserRequestClient<runtime.Types.Result.GetResult<Prisma.$UserRequestPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserRequest that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRequestFindFirstOrThrowArgs} args - Arguments to find a UserRequest
   * @example
   * // Get one UserRequest
   * const userRequest = await prisma.userRequest.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserRequestFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserRequestFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserRequestClient<runtime.Types.Result.GetResult<Prisma.$UserRequestPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserRequests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRequestFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserRequests
   * const userRequests = await prisma.userRequest.findMany()
   * 
   * // Get first 10 UserRequests
   * const userRequests = await prisma.userRequest.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userRequestWithIdOnly = await prisma.userRequest.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserRequestFindManyArgs>(args?: Prisma.SelectSubset<T, UserRequestFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserRequest.
   * @param {UserRequestCreateArgs} args - Arguments to create a UserRequest.
   * @example
   * // Create one UserRequest
   * const UserRequest = await prisma.userRequest.create({
   *   data: {
   *     // ... data to create a UserRequest
   *   }
   * })
   * 
   */
  create<T extends UserRequestCreateArgs>(args: Prisma.SelectSubset<T, UserRequestCreateArgs<ExtArgs>>): Prisma.Prisma__UserRequestClient<runtime.Types.Result.GetResult<Prisma.$UserRequestPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserRequests.
   * @param {UserRequestCreateManyArgs} args - Arguments to create many UserRequests.
   * @example
   * // Create many UserRequests
   * const userRequest = await prisma.userRequest.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserRequestCreateManyArgs>(args?: Prisma.SelectSubset<T, UserRequestCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserRequests and returns the data saved in the database.
   * @param {UserRequestCreateManyAndReturnArgs} args - Arguments to create many UserRequests.
   * @example
   * // Create many UserRequests
   * const userRequest = await prisma.userRequest.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserRequests and only return the `id`
   * const userRequestWithIdOnly = await prisma.userRequest.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserRequestCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserRequestCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRequestPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserRequest.
   * @param {UserRequestDeleteArgs} args - Arguments to delete one UserRequest.
   * @example
   * // Delete one UserRequest
   * const UserRequest = await prisma.userRequest.delete({
   *   where: {
   *     // ... filter to delete one UserRequest
   *   }
   * })
   * 
   */
  delete<T extends UserRequestDeleteArgs>(args: Prisma.SelectSubset<T, UserRequestDeleteArgs<ExtArgs>>): Prisma.Prisma__UserRequestClient<runtime.Types.Result.GetResult<Prisma.$UserRequestPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserRequest.
   * @param {UserRequestUpdateArgs} args - Arguments to update one UserRequest.
   * @example
   * // Update one UserRequest
   * const userRequest = await prisma.userRequest.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserRequestUpdateArgs>(args: Prisma.SelectSubset<T, UserRequestUpdateArgs<ExtArgs>>): Prisma.Prisma__UserRequestClient<runtime.Types.Result.GetResult<Prisma.$UserRequestPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserRequests.
   * @param {UserRequestDeleteManyArgs} args - Arguments to filter UserRequests to delete.
   * @example
   * // Delete a few UserRequests
   * const { count } = await prisma.userRequest.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserRequestDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserRequestDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRequestUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserRequests
   * const userRequest = await prisma.userRequest.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserRequestUpdateManyArgs>(args: Prisma.SelectSubset<T, UserRequestUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserRequests and returns the data updated in the database.
   * @param {UserRequestUpdateManyAndReturnArgs} args - Arguments to update many UserRequests.
   * @example
   * // Update many UserRequests
   * const userRequest = await prisma.userRequest.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserRequests and only return the `id`
   * const userRequestWithIdOnly = await prisma.userRequest.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserRequestUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserRequestUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRequestPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserRequest.
   * @param {UserRequestUpsertArgs} args - Arguments to update or create a UserRequest.
   * @example
   * // Update or create a UserRequest
   * const userRequest = await prisma.userRequest.upsert({
   *   create: {
   *     // ... data to create a UserRequest
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserRequest we want to update
   *   }
   * })
   */
  upsert<T extends UserRequestUpsertArgs>(args: Prisma.SelectSubset<T, UserRequestUpsertArgs<ExtArgs>>): Prisma.Prisma__UserRequestClient<runtime.Types.Result.GetResult<Prisma.$UserRequestPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserRequests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRequestCountArgs} args - Arguments to filter UserRequests to count.
   * @example
   * // Count the number of UserRequests
   * const count = await prisma.userRequest.count({
   *   where: {
   *     // ... the filter for the UserRequests we want to count
   *   }
   * })
  **/
  count<T extends UserRequestCountArgs>(
    args?: Prisma.Subset<T, UserRequestCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserRequestCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRequestAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserRequestAggregateArgs>(args: Prisma.Subset<T, UserRequestAggregateArgs>): Prisma.PrismaPromise<GetUserRequestAggregateType<T>>

  /**
   * Group by UserRequest.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRequestGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserRequestGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserRequestGroupByArgs['orderBy'] }
      : { orderBy?: UserRequestGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserRequestGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserRequestGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserRequest model
 */
readonly fields: UserRequestFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserRequest.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserRequestClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  chat<T extends Prisma.ChatDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChatDefaultArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  agentResponse<T extends Prisma.UserRequest$agentResponseArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserRequest$agentResponseArgs<ExtArgs>>): Prisma.Prisma__AgentResponseClient<runtime.Types.Result.GetResult<Prisma.$AgentResponsePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserRequest model
 */
export interface UserRequestFieldRefs {
  readonly id: Prisma.FieldRef<"UserRequest", 'String'>
  readonly type: Prisma.FieldRef<"UserRequest", 'String'>
  readonly text: Prisma.FieldRef<"UserRequest", 'String'>
  readonly timestamp: Prisma.FieldRef<"UserRequest", 'DateTime'>
  readonly chatId: Prisma.FieldRef<"UserRequest", 'String'>
  readonly agentResponseId: Prisma.FieldRef<"UserRequest", 'String'>
}
    

// Custom InputTypes
/**
 * UserRequest findUnique
 */
export type UserRequestFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRequest
   */
  select?: Prisma.UserRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRequest
   */
  omit?: Prisma.UserRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRequestInclude<ExtArgs> | null
  /**
   * Filter, which UserRequest to fetch.
   */
  where: Prisma.UserRequestWhereUniqueInput
}

/**
 * UserRequest findUniqueOrThrow
 */
export type UserRequestFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRequest
   */
  select?: Prisma.UserRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRequest
   */
  omit?: Prisma.UserRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRequestInclude<ExtArgs> | null
  /**
   * Filter, which UserRequest to fetch.
   */
  where: Prisma.UserRequestWhereUniqueInput
}

/**
 * UserRequest findFirst
 */
export type UserRequestFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRequest
   */
  select?: Prisma.UserRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRequest
   */
  omit?: Prisma.UserRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRequestInclude<ExtArgs> | null
  /**
   * Filter, which UserRequest to fetch.
   */
  where?: Prisma.UserRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRequests to fetch.
   */
  orderBy?: Prisma.UserRequestOrderByWithRelationInput | Prisma.UserRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserRequests.
   */
  cursor?: Prisma.UserRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserRequests.
   */
  distinct?: Prisma.UserRequestScalarFieldEnum | Prisma.UserRequestScalarFieldEnum[]
}

/**
 * UserRequest findFirstOrThrow
 */
export type UserRequestFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRequest
   */
  select?: Prisma.UserRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRequest
   */
  omit?: Prisma.UserRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRequestInclude<ExtArgs> | null
  /**
   * Filter, which UserRequest to fetch.
   */
  where?: Prisma.UserRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRequests to fetch.
   */
  orderBy?: Prisma.UserRequestOrderByWithRelationInput | Prisma.UserRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserRequests.
   */
  cursor?: Prisma.UserRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserRequests.
   */
  distinct?: Prisma.UserRequestScalarFieldEnum | Prisma.UserRequestScalarFieldEnum[]
}

/**
 * UserRequest findMany
 */
export type UserRequestFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRequest
   */
  select?: Prisma.UserRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRequest
   */
  omit?: Prisma.UserRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRequestInclude<ExtArgs> | null
  /**
   * Filter, which UserRequests to fetch.
   */
  where?: Prisma.UserRequestWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRequests to fetch.
   */
  orderBy?: Prisma.UserRequestOrderByWithRelationInput | Prisma.UserRequestOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserRequests.
   */
  cursor?: Prisma.UserRequestWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRequests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRequests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserRequests.
   */
  distinct?: Prisma.UserRequestScalarFieldEnum | Prisma.UserRequestScalarFieldEnum[]
}

/**
 * UserRequest create
 */
export type UserRequestCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRequest
   */
  select?: Prisma.UserRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRequest
   */
  omit?: Prisma.UserRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRequestInclude<ExtArgs> | null
  /**
   * The data needed to create a UserRequest.
   */
  data: Prisma.XOR<Prisma.UserRequestCreateInput, Prisma.UserRequestUncheckedCreateInput>
}

/**
 * UserRequest createMany
 */
export type UserRequestCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserRequests.
   */
  data: Prisma.UserRequestCreateManyInput | Prisma.UserRequestCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserRequest createManyAndReturn
 */
export type UserRequestCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRequest
   */
  select?: Prisma.UserRequestSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserRequest
   */
  omit?: Prisma.UserRequestOmit<ExtArgs> | null
  /**
   * The data used to create many UserRequests.
   */
  data: Prisma.UserRequestCreateManyInput | Prisma.UserRequestCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRequestIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserRequest update
 */
export type UserRequestUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRequest
   */
  select?: Prisma.UserRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRequest
   */
  omit?: Prisma.UserRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRequestInclude<ExtArgs> | null
  /**
   * The data needed to update a UserRequest.
   */
  data: Prisma.XOR<Prisma.UserRequestUpdateInput, Prisma.UserRequestUncheckedUpdateInput>
  /**
   * Choose, which UserRequest to update.
   */
  where: Prisma.UserRequestWhereUniqueInput
}

/**
 * UserRequest updateMany
 */
export type UserRequestUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserRequests.
   */
  data: Prisma.XOR<Prisma.UserRequestUpdateManyMutationInput, Prisma.UserRequestUncheckedUpdateManyInput>
  /**
   * Filter which UserRequests to update
   */
  where?: Prisma.UserRequestWhereInput
  /**
   * Limit how many UserRequests to update.
   */
  limit?: number
}

/**
 * UserRequest updateManyAndReturn
 */
export type UserRequestUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRequest
   */
  select?: Prisma.UserRequestSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserRequest
   */
  omit?: Prisma.UserRequestOmit<ExtArgs> | null
  /**
   * The data used to update UserRequests.
   */
  data: Prisma.XOR<Prisma.UserRequestUpdateManyMutationInput, Prisma.UserRequestUncheckedUpdateManyInput>
  /**
   * Filter which UserRequests to update
   */
  where?: Prisma.UserRequestWhereInput
  /**
   * Limit how many UserRequests to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRequestIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserRequest upsert
 */
export type UserRequestUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRequest
   */
  select?: Prisma.UserRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRequest
   */
  omit?: Prisma.UserRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRequestInclude<ExtArgs> | null
  /**
   * The filter to search for the UserRequest to update in case it exists.
   */
  where: Prisma.UserRequestWhereUniqueInput
  /**
   * In case the UserRequest found by the `where` argument doesn't exist, create a new UserRequest with this data.
   */
  create: Prisma.XOR<Prisma.UserRequestCreateInput, Prisma.UserRequestUncheckedCreateInput>
  /**
   * In case the UserRequest was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserRequestUpdateInput, Prisma.UserRequestUncheckedUpdateInput>
}

/**
 * UserRequest delete
 */
export type UserRequestDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRequest
   */
  select?: Prisma.UserRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRequest
   */
  omit?: Prisma.UserRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRequestInclude<ExtArgs> | null
  /**
   * Filter which UserRequest to delete.
   */
  where: Prisma.UserRequestWhereUniqueInput
}

/**
 * UserRequest deleteMany
 */
export type UserRequestDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserRequests to delete
   */
  where?: Prisma.UserRequestWhereInput
  /**
   * Limit how many UserRequests to delete.
   */
  limit?: number
}

/**
 * UserRequest.agentResponse
 */
export type UserRequest$agentResponseArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentResponse
   */
  select?: Prisma.AgentResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentResponse
   */
  omit?: Prisma.AgentResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentResponseInclude<ExtArgs> | null
  where?: Prisma.AgentResponseWhereInput
}

/**
 * UserRequest without action
 */
export type UserRequestDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRequest
   */
  select?: Prisma.UserRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRequest
   */
  omit?: Prisma.UserRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRequestInclude<ExtArgs> | null
}
